window.PC_PRODUCTS = [
  { id: "bioglutide-10mg", name: "Bioglutide 10mg", category: "all-products", categoryLabel: "All Products" },
  { id: "bioglutide-5mg", name: "Bioglutide flacon 5mg", category: "all-products", categoryLabel: "All Products" },
  { id: "servoscope-binocular-microscope", name: "Servoscope binocular microscope", category: "research-supplies", categoryLabel: "Research Supplies" },
  { id: "syn-ake-200mg", name: "Syn-ake 200mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "ru58841-2000mg", name: "Ru58841 2000mg topical vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "tbl150rad150-100x10mg-copy", name: "TBL-150(rad150) 1g", category: "sarms", categoryLabel: "Sarms" },
  { id: "retinalamin-10mg", name: "Retinalamin 10mg", category: "peptides", categoryLabel: "Peptides" },
  { id: "thymalfasin-20mg-vial", name: "Thymalfasin 20mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "tbl150rad150-50x10mg", name: "TBL150(rad150) 100x10mg", category: "pellets-pill", categoryLabel: "Pellets (pill)" },
  { id: "plastic-test-tube-rack-for-60-tubes", name: "Plastic test tube rack", category: "research-supplies", categoryLabel: "Research Supplies" },
  { id: "pnc-27-10mg-vial", name: "PNC-27 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "pp405-10mg-vial", name: "PP405 10mg vial", category: "other-products", categoryLabel: "Other products" },
  { id: "microscope-cover-slips-200pcs", name: "Microscope cover slips 200pcs", category: "research-supplies", categoryLabel: "Research Supplies" },
  { id: "argirelin-200mg-vial", name: "Argirelin 200mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "vesilute-20mg", name: "Vesilute 20mg", category: "peptides", categoryLabel: "Peptides" },
  { id: "larazotide-10mg-vial", name: "Larazotide 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "ptd-1-1mg", name: "PTD-1 1mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "hep-1-10mg-vial", name: "HEP-1 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "yk-11-5x50mg", name: "YK-11 100x10mg", category: "sarms", categoryLabel: "Sarms" },
  { id: "yk-11-1gr", name: "YK-11 1gr", category: "powder", categoryLabel: "Powder" },
  { id: "ampoule-opener", name: "Ampoule opener", category: "research-supplies", categoryLabel: "Research Supplies" },
  { id: "double-sample-transport-bags-160-200-mm-10pc", name: "Double sample transport bags (160×200 mm) 10pc", category: "research-supplies", categoryLabel: "Research Supplies" },
  { id: "centrifuge-tubes-100pc", name: "Centrifuge tubes 100pc", category: "research-supplies", categoryLabel: "Research Supplies" },
  { id: "3-section-petri-dishes-20pc", name: "3-section Petri dishes 20pc", category: "research-supplies", categoryLabel: "Research Supplies" },
  { id: "humanin-10mg-vial", name: "Humanin 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "thymosin-β4-fragment-17-24-10mg-vial", name: "Thymosin β4 Fragment 17–24 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "dnsp-11-10mg-vial", name: "DNSP-11 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "safety-glasses", name: "Safety glasses", category: "research-supplies", categoryLabel: "Research Supplies" },
  { id: "medical-masks-3-layer-type-iir", name: "medical masks 3-layer Type IIR", category: "research-supplies", categoryLabel: "Research Supplies" },
  { id: "mots-c-40mg-vial", name: "MOTS-c 40mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "hng-10mg-vial", name: "HNG 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "nad-500mg-vial", name: "NAD+ 500mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "alcohol-swipes-6x3cm-100pc", name: "Alcohol swipes 6x3cm 100pc", category: "research-supplies", categoryLabel: "Research Supplies" },
  { id: "cb-03-01-clascoterone-1000mg-vial", name: "CB-03-01 (clascoterone) 1000mg vial", category: "other-products", categoryLabel: "Other products" },
  { id: "pal-ghk-10mg", name: "PAL-GHK 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "latex-gloves-150pc", name: "Latex Gloves 150pc", category: "all-products", categoryLabel: "All Products" },
  { id: "lab-coat-unisex", name: "Lab coat unisex", category: "research-supplies", categoryLabel: "Research Supplies" },
  { id: "dermorphin-10mg-vial", name: "Dermorphin 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "orexin-a-10mg-vial", name: "Orexin A 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "orexin-b-10mg-vial", name: "Orexin B 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "chrysalin", name: "Chrysalin 10mg", category: "peptides", categoryLabel: "Peptides" },
  { id: "fgl-10mg-vial", name: "FGL 30mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "epitalon-50mg-vial", name: "Epitalon 50mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "igf1-lr3-1mg-vial", name: "IGF1-LR3 1mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "colivelin-10mg-vial", name: "Colivelin 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "embryonic-stem-cells-vial", name: "Embryonic stem cells ampoule", category: "other-products", categoryLabel: "Other products" },
  { id: "astressin-b-10mg-vial", name: "Astressin-B 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "ghk-cu-100mg-vial", name: "GHK-CU 100mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "survodutide-10mg-vial", name: "Survodutide 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "ac-262-10x60mg", name: "AC-262 100x10mg", category: "pellets-pill", categoryLabel: "Pellets (pill)" },
  { id: "noopept-10mgx90", name: "Noopept 100x10mg", category: "nootropics", categoryLabel: "Nootropics" },
  { id: "cerebrolysin-60mg-vial", name: "Cerebrolysin 60mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "retratrutide-5mg-vial", name: "Retatrutide 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "slu-pp-332-200mcgx60", name: "SLU-PP-332 20.000mcg sublingual/oral vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "epitalon-10mg-vial", name: "Epitalon 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "ipamorelin-10mg-vial", name: "Ipamorelin 10mg vial", category: "gh-analogs-and-secretagogues", categoryLabel: "GH Analogs and Secretagogues" },
  { id: "ghrp-6-10mg-vial", name: "GHRP-6 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "cjc-1295", name: "CJC-1295 10mg vial", category: "gh-analogs-and-secretagogues", categoryLabel: "GH Analogs and Secretagogues" },
  { id: "ace-031-1mg-vial", name: "ACE-031 1mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "injectable-yk-11-700mg-vial", name: "Injectable YK-11 700mg vial", category: "myostatin-inhibitors", categoryLabel: "Myostatin Inhibitors" },
  { id: "ace-083-1-mg-vial", name: "ACE-083 1 mg vial", category: "myostatin-inhibitors", categoryLabel: "Myostatin Inhibitors" },
  { id: "follistatin-344-1mg-vial", name: "Follistatin344 1mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "lgd-4033-50x10mg", name: "LGD-4033 100x10mg", category: "pellets-pill", categoryLabel: "Pellets (pill)" },
  { id: "rad140-50x10mg", name: "RAD-140 100x10mg", category: "sarms", categoryLabel: "Sarms" },
  { id: "ostarine-50x10mg", name: "MK2886(Ostarine) 100x10mg", category: "sarms", categoryLabel: "Sarms" },
  { id: "s4andarine-50x50mg", name: "S4(Andarine) 100x50mg", category: "pellets-pill", categoryLabel: "Pellets (pill)" },
  { id: "5ml-syringe", name: "5ml Syringe", category: "research-supplies", categoryLabel: "Research Supplies" },
  { id: "3ml-pipette", name: "3ml Pipette", category: "research-supplies", categoryLabel: "Research Supplies" },
  { id: "100ml-measuring-cup", name: "100ml Measuring cup", category: "all-products", categoryLabel: "All Products" },
  { id: "bpc157-10mg-vial", name: "BPC-157 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "ansulinespuit", name: "Insulin needles(10) 29g 0,5ml", category: "research-supplies", categoryLabel: "Research Supplies" },
  { id: "methylene-blue-60ml-usp-grade", name: "Methylene blue USP grade 100x10mg", category: "nootropics", categoryLabel: "Nootropics" },
  { id: "tb500-10mg-vial", name: "TB500 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "bac-water-10ml-vial", name: "BAC water 10ml vial", category: "gh-analogs-and-secretagogues", categoryLabel: "GH Analogs and Secretagogues" },
  { id: "acp105-60x10mg", name: "ACP-105 100x10mg", category: "sarms", categoryLabel: "Sarms" },
  { id: "s23-60x10-mg", name: "S23 100x10mg", category: "sarms", categoryLabel: "Sarms" },
  { id: "30g-13mm-needle", name: "29g 13mm needle 100pcs", category: "research-supplies", categoryLabel: "Research Supplies" },
  { id: "enclomiphene-50x12-5mg", name: "Enclomiphene Citrate 100x12.5mg", category: "pellets-pill", categoryLabel: "Pellets (pill)" },
  { id: "gw-50186cardarine-60x10mg", name: "GW-501516(Cardarine) 100x10mg", category: "sarms", categoryLabel: "Sarms" },
  { id: "gw0742-60x10mg", name: "GW0742 100x10mg", category: "pellets-pill", categoryLabel: "Pellets (pill)" },
  { id: "sr9009stenabolic-60x10mg", name: "SR9009(Stenabolic) 100x10mg", category: "pellets-pill", categoryLabel: "Pellets (pill)" },
  { id: "ghk-cu-50mg-vial", name: "GHK-CU 50mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "igf1-des-1mg-vial", name: "IGF1-Des 2mg vial", category: "gh-analogs-and-secretagogues", categoryLabel: "GH Analogs and Secretagogues" },
  { id: "mots-c-10mg-vial", name: "MOTS-c 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "dsip-10mg-vial", name: "DSIP 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "peg-mgf-5mg-vial", name: "PEG-MGF 5mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "5-amino-1-mq-60x50mg", name: "5-Amino-1-MQ 100x50mg", category: "pellets-pill", categoryLabel: "Pellets (pill)" },
  { id: "melanotan-ii-10mg-vial", name: "Melanotan-II 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "lgd3033-60x7-5mg", name: "LGD-3033 100x10mg", category: "sarms", categoryLabel: "Sarms" },
  { id: "dihexa-60x10mg", name: "Dihexa 100x10mg", category: "nootropics", categoryLabel: "Nootropics" },
  { id: "selank-10mg-vial", name: "Selank 10mg vial", category: "nasal", categoryLabel: "Nasal" },
  { id: "semax-10mg-vial", name: "Semax 10mg vial", category: "nasal", categoryLabel: "Nasal" },
  { id: "kpv-10mg-vial", name: "KPV 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "kisspeptin-10-10mg-vial", name: "Kisspeptin-10 10mg vial", category: "gonadotropins", categoryLabel: "Gonadotropins" },
  { id: "pt-141-10mg-vial", name: "PT-141 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "bromantane-60x25mg", name: "Bromantane 100x30mg", category: "pellets-pill", categoryLabel: "Pellets (pill)" },
  { id: "phenibut-hcl-90x200mg", name: "Phenibut HCL 100x200mg", category: "nootropics", categoryLabel: "Nootropics" },
  { id: "nsi-189-60x30mg", name: "NSI-189 100x30mg", category: "pellets-pill", categoryLabel: "Pellets (pill)" },
  { id: "9-mbc-60x25mg", name: "9-MBC 100x25mg", category: "nootropics", categoryLabel: "Nootropics" },
  { id: "injectable-s23-400mg-vial", name: "Injectable RAD140 500mg vial", category: "sarms", categoryLabel: "Sarms" },
  { id: "injectable-s23-400mg-vial-1", name: "Injectable S-23 400mg vial", category: "sarms", categoryLabel: "Sarms" },
  { id: "injectable-lgd4033-250mg-vial", name: "Injectable LGD4033 250mg vial", category: "sarms", categoryLabel: "Sarms" },
  { id: "bpc-157-pellets-500mcgx100", name: "BPC-157 pellets 100x500mcg", category: "pellets-pill", categoryLabel: "Pellets (pill)" },
  { id: "foxo4-dri-10mg-vial", name: "FOXO4-DRI 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "l-carnitine-500mg", name: "L-carnitine 5000mg flacon", category: "peptides", categoryLabel: "Peptides" },
  { id: "gdf-8-2mg", name: "GDF-8 2mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "cagrilintide-10mg", name: "Cagrilintide 10mg vial", category: "glp-1", categoryLabel: "GLP-1" },
  { id: "aod9604-5mg-vial", name: "AOD9604 5mg vial", category: "gh-analogs-and-secretagogues", categoryLabel: "GH Analogs and Secretagogues" },
  { id: "oxytocin-acetate-2mg-vial", name: "Oxytocin Acetate 10mg vial", category: "nootropics", categoryLabel: "Nootropics" },
  { id: "mazdutide-10mg-vial", name: "Mazdutide 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "ara290-10mg-vial", name: "ARA290 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "pinealon-10mg-vial", name: "Pinealon 20mg vial", category: "nootropics", categoryLabel: "Nootropics" },
  { id: "vilon-5mg-vial", name: "Vilon 20mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "ss-31-10mg-vial", name: "SS-31 50mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "lipo-c-10mg-vial", name: "Lipo-c 10mg vial", category: "glp-1", categoryLabel: "GLP-1" },
  { id: "snap-8-10mg-vial", name: "Snap-8 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "bam15-100x15mg", name: "BAM15 100x15mg", category: "other-products", categoryLabel: "Other products" },
  { id: "sobetiromegc-1", name: "Sobetirome(GC-1) 10.000mcg sublingual/oral vial", category: "pellets-pill", categoryLabel: "Pellets (pill)" },
  { id: "10ml-reusable-nasal-spray-bottle", name: "10ml Reusable nasal spray bottle", category: "nasal", categoryLabel: "Nasal" },
  { id: "follistatin344-5mg-vial", name: "Follistatin344 5mg vial", category: "myostatin-inhibitors", categoryLabel: "Myostatin Inhibitors" },
  { id: "rad140-1gr", name: "RAD-140 1g", category: "sarms", categoryLabel: "Sarms" },
  { id: "livagen-20mg-vial", name: "Livagen 20mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "prostamax-20mg-vial", name: "Prostamax 20mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "noopept-1g", name: "Noopept 1g", category: "powder", categoryLabel: "Powder" },
  { id: "lgd3033-1g", name: "LGD3033 1g", category: "powder", categoryLabel: "Powder" },
  { id: "sermorelin-10mg-vial", name: "Sermorelin 10mg vial", category: "gh-analogs-and-secretagogues", categoryLabel: "GH Analogs and Secretagogues" },
  { id: "rhgh-fragment-176-191-10mg-vial", name: "rHGH Fragment 176–191 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "tesamorelin-10mg-vial", name: "Tesamorelin 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "ghrp-2-10mg", name: "GHRP-2 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "gonadorelin-10mg-vial", name: "Gonadorelin 10mg vial", category: "gonadotropins", categoryLabel: "Gonadotropins" },
  { id: "triptorelin-acetate-10mg", name: "Triptorelin Acetate 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "hexarelin-10mg-vial", name: "Hexarelin 10mg vial", category: "gh-analogs-and-secretagogues", categoryLabel: "GH Analogs and Secretagogues" },
  { id: "cjc-1295-with-dac-10mg-vial", name: "CJC-1295 with DAC 10mg vial", category: "gh-analogs-and-secretagogues", categoryLabel: "GH Analogs and Secretagogues" },
  { id: "thymalin-10mg-vial", name: "Thymalin 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "thymosin-alpha-1-10mg-vial", name: "Thymosin alpha-1 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "ll-37-5mg-vial", name: "LL-37 5mg vial", category: "nasal", categoryLabel: "Nasal" },
  { id: "5-amino-1-mq-5mg-vial", name: "5-Amino-1-MQ 50mg vial", category: "nasal", categoryLabel: "Nasal" },
  { id: "slu-pp-332-5mg-vial", name: "SLU-pp-332 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "mk677ibutamoren-100x10mgg", name: "MK677(Ibutamoren) 100x10mg", category: "sarms", categoryLabel: "Sarms" },
  { id: "191aa-somatropin-150iu-kit", name: "191AA Somatropin 150iu kit", category: "gh-analogs-and-secretagogues", categoryLabel: "GH Analogs and Secretagogues" },
  { id: "191aa-somatropin-100iu-kit", name: "191aa Somatropin 100iu kit", category: "gh-analogs-and-secretagogues", categoryLabel: "GH Analogs and Secretagogues" },
  { id: "glow-70mg10mg-bpc157-10mg-tb500-50mg-ghk-cu", name: "GLOW 70mg", category: "peptides", categoryLabel: "Peptides" },
  { id: "human-chorionic-gonadotropinhcg-5000iu-vial", name: "Human chorionic gonadotropin(HCG) 5000iu vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "lgd4033-1g", name: "LGD4033 1g", category: "sarms", categoryLabel: "Sarms" },
  { id: "mk777-10ng", name: "MK777 100x10mg", category: "gh-analogs-and-secretagogues", categoryLabel: "GH Analogs and Secretagogues" },
  { id: "tudca-100x500mg", name: "TUDCA 100x500mg", category: "other-products", categoryLabel: "Other products" },
  { id: "bioglutide", name: "Bioglutide 100x100mg", category: "pellets-pill", categoryLabel: "Pellets (pill)" },
  { id: "mk777-100x10mg-copy", name: "MK777 1g", category: "gh-analogs-and-secretagogues", categoryLabel: "GH Analogs and Secretagogues" },
  { id: "slu-pp-332-1g1000mg", name: "SLU-pp-332 1g", category: "peptides", categoryLabel: "Peptides" },
  { id: "enclomiphene-citrate-100x12-5mg-copy", name: "Enclomiphene Citrate 1g", category: "powder", categoryLabel: "Powder" },
  { id: "bromantane-1g", name: "Bromantane 1g", category: "nootropics", categoryLabel: "Nootropics" },
  { id: "mk2886ostarine-1g", name: "MK2886(Ostarine) 1g", category: "sarms", categoryLabel: "Sarms" },
  { id: "bam15-1g", name: "BAM15 1g", category: "other-products", categoryLabel: "Other products" },
  { id: "dihexa-1g", name: "Dihexa 1g", category: "nootropics", categoryLabel: "Nootropics" },
  { id: "9-mbc-1g", name: "9-MBC 1g", category: "nootropics", categoryLabel: "Nootropics" },
  { id: "nsi-189-1g", name: "NSI-189 1g", category: "nootropics", categoryLabel: "Nootropics" },
  { id: "gw0742-1g", name: "GW0742 1g", category: "sarms", categoryLabel: "Sarms" },
  { id: "ru58841-1g", name: "Ru58841 1g", category: "peptides", categoryLabel: "Peptides" },
  { id: "gw-501516cardarine-1g", name: "GW-501516(Cardarine) 1g", category: "powder", categoryLabel: "Powder" },
  { id: "s23-1g", name: "S23 1g", category: "powder", categoryLabel: "Powder" },
  { id: "s4andarine-1g", name: "S4(Andarine) 1g", category: "sarms", categoryLabel: "Sarms" },
  { id: "klow-80mg-vial", name: "KLOW 80mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "hmg-75-iu-vial", name: "HMG 75 IU vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "cartalax-20mg-vial", name: "Cartalax 20mg vial", category: "bioregulators", categoryLabel: "Bioregulators" },
  { id: "testagen-20mg-vial", name: "Testagen 20mg vial", category: "bioregulators", categoryLabel: "Bioregulators" },
  { id: "bronchogen-20mg-vial", name: "Bronchogen 20mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "cardiogen-20mg-vial", name: "Cardiogen 20mg vial", category: "bioregulators", categoryLabel: "Bioregulators" },
  { id: "trevogrumab-10mg", name: "Trevogrumab (REGN1033 / SAR391786) 10mg", category: "monoclonal-antibodies-mabs", categoryLabel: "Monoclonal Antibodies (mAbs)" },
  { id: "garetosmab-regn2477-10mg", name: "Garetosmab (REGN2477) 10mg", category: "monoclonal-antibodies-mabs", categoryLabel: "Monoclonal Antibodies (mAbs)" },
  { id: "p21-with-adamantane-10mg-vial", name: "P21 with adamantane 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "tb500-100x500mcg", name: "TB500 100x500mcg", category: "peptides", categoryLabel: "Peptides" },
  { id: "kpv-100x500mcg", name: "KPV 100x500mcg", category: "peptides", categoryLabel: "Peptides" },
  { id: "pe-22-28-10mg-vial", name: "PE-22-28 10mg vial", category: "nootropics", categoryLabel: "Nootropics" },
  { id: "aod9604-10mg-vial", name: "AOD9604 10mg vial", category: "gh-analogs-and-secretagogues", categoryLabel: "GH Analogs and Secretagogues" },
  { id: "vip-10mg-vial", name: "VIP 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "vesugen-20mg-vial", name: "Vesugen 20mg vial", category: "bioregulators", categoryLabel: "Bioregulators" },
  { id: "ovagen-20mg-vial", name: "Ovagen 20mg vial", category: "bioregulators", categoryLabel: "Bioregulators" },
  { id: "crystagen-20mg-vial", name: "Crystagen 20mg vial", category: "bioregulators", categoryLabel: "Bioregulators" },
  { id: "adamax-10mg-vial", name: "Adamax 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "cortagen-20mg-vial", name: "Cortagen 20mg vial", category: "bioregulators", categoryLabel: "Bioregulators" },
  { id: "pancragen-20mg-vial", name: "Pancragen 20mg vial", category: "bioregulators", categoryLabel: "Bioregulators" },
  { id: "matrixyl-10mg-vial", name: "Matrixyl 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "chonluten-20mg-vial", name: "Chonluten 20mg vial", category: "bioregulators", categoryLabel: "Bioregulators" },
  { id: "teriparatide-10mg-vial", name: "Teriparatide 10mg vial", category: "bioregulators", categoryLabel: "Bioregulators" },
  { id: "stamulumab-myo-029-10mg", name: "Stamulumab (MYO-029) 10mg", category: "monoclonal-antibodies-mabs", categoryLabel: "Monoclonal Antibodies (mAbs)" },
  { id: "landogrozumab-ly2495655-10mg", name: "Landogrozumab (LY2495655) 10mg", category: "monoclonal-antibodies-mabs", categoryLabel: "Monoclonal Antibodies (mAbs)" },
  { id: "bimagrumab-bym338-10mg", name: "Bimagrumab (BYM338) 10mg", category: "monoclonal-antibodies-mabs", categoryLabel: "Monoclonal Antibodies (mAbs)" },
  { id: "sabatolimab-mbg453-10mg", name: "Sabatolimab (MBG453) 10mg", category: "monoclonal-antibodies-mabs", categoryLabel: "Monoclonal Antibodies (mAbs)" },
  { id: "domagrozumab-pf-06252616-10mg", name: "Domagrozumab (PF-06252616) 10mg", category: "monoclonal-antibodies-mabs", categoryLabel: "Monoclonal Antibodies (mAbs)" },
  { id: "tiragolumabrg6058-mtig7192a-10mg", name: "Tiragolumab(RG6058/MTIG7192A) 10mg", category: "monoclonal-antibodies-mabs", categoryLabel: "Monoclonal Antibodies (mAbs)" },
  { id: "ahk-cu-100mg-vial", name: "AHK-CU 100mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "slu-pp-332-100x10mg", name: "SLU-pp-332 100x10mg", category: "peptides", categoryLabel: "Peptides" },
  { id: "tesofensine-500mcgx100", name: "Tesofensine 500mcgx100", category: "other-products", categoryLabel: "Other products" },
  { id: "aicar-100mg", name: "AICAR 100mg", category: "peptides", categoryLabel: "Peptides" },
  { id: "bac-water-3ml-vial", name: "BAC water 3ml vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "b7-33-10mg-vial", name: "B7-33 10mg vial", category: "peptides", categoryLabel: "Peptides" },
  { id: "slu-pp-332-100x5mg", name: "SLU-pp-332 100x5mg", category: "peptides", categoryLabel: "Peptides" },
  { id: "melatonin-10mg-vial", name: "Melatonin 10mg vial", category: "nootropics", categoryLabel: "Nootropics" },
  { id: "adipotide-5mg-vial", name: "Adipotide 5mg vial", category: "glp-1", categoryLabel: "GLP-1" },
  { id: "retatrutide-20mg-vial", name: "Retatrutide 20mg vial", category: "glp-1", categoryLabel: "GLP-1" },
  { id: "retatrutide-30mg-vial", name: "Retatrutide 30mg vial", category: "glp-1", categoryLabel: "GLP-1" },
];
